"""Add password management and visa case status fields

Revision ID: 946cb5a52494
Revises: a69ae56740fc
Create Date: 2025-11-03 10:31:04.258086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946cb5a52494'
down_revision: Union[str, None] = 'a69ae56740fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with defaults for existing rows
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_change_count', sa.String(length=50), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('invitation_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('invitation_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('invitation_accepted', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('visa_applications', sa.Column('case_status', sa.Enum('UPCOMING', 'ACTIVE', 'FINALIZED', name='visacasestatus'), nullable=False, server_default='ACTIVE'))
    op.create_index(op.f('ix_visa_applications_case_status'), 'visa_applications', ['case_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visa_applications_case_status'), table_name='visa_applications')
    op.drop_column('visa_applications', 'case_status')
    op.drop_column('users', 'invitation_accepted')
    op.drop_column('users', 'invitation_token_expires')
    op.drop_column('users', 'invitation_token')
    op.drop_column('users', 'password_change_count')
    op.drop_column('users', 'password_reset_token_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'force_password_change')
    # ### end Alembic commands ###
